name: GitHub Pages Submission
description: Submit your GitHub Pages assignment
title: "Submission: <Your Name and Register Number>"
labels: ["submission"]
body:
  - type: input
    id: name
    attributes:
      label: Your Full Name
      placeholder: "e.g., Anu B"
    validations:
      required: true

  - type: input
    id: reg
    attributes:
      label: Register Number
      placeholder: "e.g., 22CS001"
    validations:
      required: true

  - type: input
    id: pages_link
    attributes:
      label: Website Link
      placeholder: "https://username.github.com/blog"
    validations:
      required: true
