name: GitHub Website Submission
description: Submit your GitHub Blog 
title: ""
labels: ["submission"]
body:
  - type: input
    id: name
    attributes:
      label: Your Full Name
      placeholder: "e.g., Barry Allen"
    validations:
      required: true

  - type: input
    id: reg
    attributes:
      label: Register Number
      placeholder: "e.g., 25CYS007"
    validations:
      required: true

  - type: input
    id: pages_link
    attributes:
      label: Website Link
      placeholder: "https://username.github.com/blog"
    validations:
      required: true
